services:
  - type: web
    name: nguyen-thanh-tai-blog
    env: python
    buildCommand: |
      # Install Python dependencies
      cd cms-backend
      pip install -r requirements.txt
      # Install Node.js dependencies and build React app
      cd ../cms-frontend
      npm install
      npm run build
      # Copy built frontend to backend static folder
      cd ../cms-backend
      rm -rf static/*
      cp -r ../cms-frontend/build/* static/
    startCommand: |
      cd cms-backend
      gunicorn --bind 0.0.0.0:$PORT app_unified:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app_unified.py
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: blog-database
          property: connectionString
    healthCheckPath: /
    regions:
      - oregon
    
databases:
  - name: blog-database
    databaseName: blog_cms
    user: blog_user