services:
  - type: web
    name: nguyen-thanh-tai-blog
    env: python
    buildCommand: |
      # Install Python dependencies only
      cd cms-backend
      pip install -r requirements.txt
      # Static files should already be committed to repo
      echo "=== Checking committed static files ==="
      ls -la static/ || echo "No static directory in repo"
      ls -la static/js/ || echo "No js directory in repo"
      ls -la static/css/ || echo "No css directory in repo"
      ls -la templates/ || echo "No templates directory in repo"
      echo "=== Build complete - using committed static files ==="
    startCommand: |
      cd cms-backend
      echo "=== Production startup debug ==="
      pwd
      ls -la static/ || echo "No static directory"
      ls -la static/js/ || echo "No js directory" 
      ls -la static/css/ || echo "No css directory"
      ls -la templates/ || echo "No templates directory"
      echo "=== Starting gunicorn ==="
      gunicorn --bind 0.0.0.0:$PORT app_unified:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app_unified.py
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: blog-database
          property: connectionString
    healthCheckPath: /
    regions:
      - oregon
    
databases:
  - name: blog-database
    databaseName: blog_cms
    user: blog_user