services:
  - type: web
    name: nguyen-thanh-tai-blog
    env: python
    buildCommand: |
      # Install Python dependencies
      cd cms-backend  
      pip install -r requirements.txt
      # Build React frontend and copy files correctly
      cd ../cms-frontend
      npm install
      npm run build
      # Clean and prepare backend directories
      cd ../cms-backend
      rm -rf static/*
      mkdir -p static/js static/css templates
      # Copy files with correct structure
      cp -r ../cms-frontend/build/static/js/* ./static/js/
      cp -r ../cms-frontend/build/static/css/* ./static/css/
      cp ../cms-frontend/build/index.html ./templates/
      cp ../cms-frontend/build/manifest.json ./
      # Verify structure
      echo "=== Final structure ==="
      ls -la static/
      ls -la static/js/
      ls -la static/css/
    startCommand: |
      cd cms-backend
      echo "=== Production startup debug ==="
      pwd
      ls -la static/ || echo "No static directory"
      ls -la static/js/ || echo "No js directory" 
      ls -la static/css/ || echo "No css directory"
      ls -la templates/ || echo "No templates directory"
      echo "=== Starting gunicorn ==="
      gunicorn --bind 0.0.0.0:$PORT app_unified:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app_unified.py
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: blog-database
          property: connectionString
    healthCheckPath: /
    regions:
      - oregon
    
databases:
  - name: blog-database
    databaseName: blog_cms
    user: blog_user