services:
  - type: web
    name: my-blog-cms
    env: python
    buildCommand: |
      # Install Python dependencies
      cd cms-backend
      pip install -r requirements.txt
      cd ../cms-frontend
      # Install Node.js dependencies and build React app
      npm install
      npm run build
      # Copy built frontend to backend static folder
      rm -rf ../cms-backend/static/*
      cp -r build/* ../cms-backend/static/
    startCommand: |
      cd cms-backend
      gunicorn --bind 0.0.0.0:$PORT app_unified:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: blog-database
          property: connectionString
    healthCheckPath: /api/posts
    
databases:
  - name: blog-database
    databaseName: blog_cms
    user: blog_user